/**
 * Regression tests for `server/src/aiDispatch/speech/precachePhrases.ts`.
 *
 * The precache list is what the ElevenLabs TTS warm-up renders on boot so
 * that the most common dispatcher responses ("Copy 040, 10-8.", "352,
 * copy. Standby.") play back from a cached buffer instead of incurring a
 * 200–600 ms streaming round-trip on the air. A regression that drops a
 * phrase from the list does not break anything visibly — it just adds a
 * fresh per-call TTS latency on the most-spoken acks, which is exactly the
 * kind of slow-drift problem that's hard to catch in manual testing.
 *
 * What this suite pins:
 *
 *  - Generic acks ("Copy", "10-4", "Standby", "Negative", "Affirm", …)
 *    are always included regardless of unit list.
 *  - Per-unit "Copy <unit>, 10-X" lines are emitted for every patrol
 *    unit × the documented 10-code set (10-8, 10-7, 10-23, 10-97, 10-98,
 *    10-19, code 4). A missing combination forces a full TTS round-trip
 *    on every status change for that unit, which is the highest-volume
 *    voice on the channel.
 *  - Command-staff "27-0X0, copy. Standby." standby acks are present for
 *    every documented command callsign — those are the ones the AI
 *    speaks while it waits on an async web lookup, so missing-precache
 *    here is the most-noticeable slow-down.
 *  - The function returns a deduped list (Set semantics) — duplicates
 *    waste warm-up time and inflate cache size on a per-process basis.
 *
 * `normalizeForTtsPrecache` is what the TTS layer uses to look up "is
 * this phrase already cached?" before kicking off a stream. The same
 * normalisation runs on both the cache key write and the runtime lookup,
 * so a regression that changes one side silently busts the cache.
 */

import { test } from "node:test";
import assert from "node:assert/strict";

import {
  buildPrecachePhraseList,
  normalizeForTtsPrecache,
} from "../../../src/aiDispatch/speech/precachePhrases.js";

const RADIO_UNITS = ["151", "231", "334", "351", "352", "401", "402", "403"];
const COMMAND_UNITS = ["27-000", "27-010", "27-020", "27-030"];
const STATUS_CODES = ["10-8", "10-7", "10-23", "10-97", "10-98", "10-19", "code 4"];

test("buildPrecachePhraseList: returns a non-empty, fully-deduped phrase set", () => {
  const list = buildPrecachePhraseList();
  assert.ok(list.length > 0, "precache list must not be empty");
  // The implementation uses a Set; verify the contract by checking that
  // the returned array has no duplicates. Two phrases coincidentally
  // generated by separate loops would otherwise both make it to TTS warm.
  const unique = new Set(list);
  assert.equal(
    unique.size,
    list.length,
    "buildPrecachePhraseList must return a deduplicated array",
  );
});

test("buildPrecachePhraseList: always includes the generic dispatcher acks", () => {
  const list = new Set(buildPrecachePhraseList());
  for (const generic of [
    "Copy",
    "10-4",
    "Standby",
    "Negative",
    "Affirm",
    "That's affirm",
    "Received",
    "I copy",
    "Roger",
  ]) {
    assert.ok(
      list.has(generic),
      `generic ack ${JSON.stringify(generic)} must be precached`,
    );
  }
});

test("buildPrecachePhraseList: 'Copy <unit>' is precached for every patrol unit", () => {
  const list = new Set(buildPrecachePhraseList());
  for (const u of RADIO_UNITS) {
    assert.ok(
      list.has(`Copy ${u}`),
      `'Copy ${u}' must be precached so the most common ack plays instantly`,
    );
  }
});

test("buildPrecachePhraseList: '<unit>, 913' info-clear ack is precached for every patrol unit", () => {
  // 913 is the radio clear-info code; the AI speaks it as the last word
  // on every info-request follow-up, so missing precache here adds latency
  // to the tail of every "what's at account 1019" response.
  const list = new Set(buildPrecachePhraseList());
  for (const u of RADIO_UNITS) {
    assert.ok(
      list.has(`${u}, 913`),
      `'${u}, 913' must be precached`,
    );
  }
});

test("buildPrecachePhraseList: 'Copy <unit>, <status>' is precached for every status code × patrol unit", () => {
  const list = new Set(buildPrecachePhraseList());
  for (const u of RADIO_UNITS) {
    for (const code of STATUS_CODES) {
      assert.ok(
        list.has(`Copy ${u}, ${code}`),
        `'Copy ${u}, ${code}' (status change ack) must be precached`,
      );
    }
  }
});

test("buildPrecachePhraseList: 'Affirm <unit>, 10-2' and the generic 10-2 ack are precached for every patrol unit", () => {
  // Used on radio-check ("10-2" = "loud and clear"). Missing precache
  // adds noticeable latency to literally the first thing said when a
  // unit comes up on the air.
  const list = new Set(buildPrecachePhraseList());
  for (const u of RADIO_UNITS) {
    assert.ok(list.has(`Affirm ${u}, 10-2`), `'Affirm ${u}, 10-2' must be precached`);
  }
  assert.ok(list.has("Affirm, you're 10-2"), "generic 'Affirm, you're 10-2' must be precached");
});

test("buildPrecachePhraseList: standby acks are precached for every patrol AND command callsign", () => {
  // Standby is what the AI speaks while a web lookup runs (see
  // infoRequestNeedsAsync). A precache miss here makes the most
  // user-facing latency window in the whole engine appreciably worse.
  const list = new Set(buildPrecachePhraseList());
  assert.ok(list.has("Copy. Standby."), "generic 'Copy. Standby.' must be precached");
  for (const u of RADIO_UNITS) {
    assert.ok(
      list.has(`${u}, copy. Standby.`),
      `'${u}, copy. Standby.' must be precached`,
    );
  }
  for (const u of COMMAND_UNITS) {
    assert.ok(
      list.has(`${u}, copy. Standby.`),
      `command callsign '${u}, copy. Standby.' must be precached`,
    );
  }
});

// ----- normalizeForTtsPrecache --------------------------------------------

test("normalizeForTtsPrecache: trims, lowercases, collapses whitespace, strips trailing punctuation", () => {
  // All five cosmetic differences MUST collapse to the same cache key or
  // the runtime TTS lookup misses and re-renders an already-cached
  // phrase, defeating the whole point of the precache. Note: the helper
  // does its replace passes in a fixed order (trim → collapse whitespace
  // → strip trailing .!? → lowercase), so the trailing-punctuation strip
  // does not re-trim — variants with whitespace BEFORE the punctuation
  // are intentionally excluded from this set and covered below.
  for (const variant of [
    "Copy 040.",
    " Copy 040",
    "copy 040!",
    "COPY   040?",
    "Copy\t040",
  ]) {
    assert.equal(
      normalizeForTtsPrecache(variant),
      "copy 040",
      `variant ${JSON.stringify(variant)} must normalise to "copy 040"`,
    );
  }
});

test("normalizeForTtsPrecache: only the final run of .!? is stripped (mid-phrase punctuation stays)", () => {
  // "10-4, copy" — the comma stays (only .!? are trimmed, and only at the
  // very end of the string). A regression that lowercased AND stripped
  // commas would collapse different phrases together and serve the wrong
  // cached buffer.
  assert.equal(normalizeForTtsPrecache("10-4, copy."), "10-4, copy");
  assert.equal(normalizeForTtsPrecache("10-4, copy"), "10-4, copy");
  assert.equal(normalizeForTtsPrecache("10-4, copy!!!"), "10-4, copy");
  assert.equal(normalizeForTtsPrecache("10-4, copy?!"), "10-4, copy");
});

test("normalizeForTtsPrecache: coerces non-string input without throwing", () => {
  // The caller occasionally passes a value of unknown provenance (LLM
  // output that the model decorated with an unexpected type, etc.). The
  // normaliser must coerce-and-trim rather than throw, otherwise a single
  // bad call kills the warm-up loop on boot.
  assert.equal(normalizeForTtsPrecache(123 as unknown as string), "123");
  assert.equal(normalizeForTtsPrecache(0 as unknown as string), "0");
});

test("buildPrecachePhraseList consistently matches normalizeForTtsPrecache (cache lookups will hit)", () => {
  // The contract that ties the two halves together: every phrase in the
  // precache list, when normalised, has a stable lookup key. Pin a few
  // representative samples so a future change to either normaliser or
  // builder is forced through this gate.
  assert.equal(normalizeForTtsPrecache("Copy 040, 10-8"), "copy 040, 10-8");
  assert.equal(normalizeForTtsPrecache("27-020, copy. Standby."), "27-020, copy. standby");
  assert.equal(normalizeForTtsPrecache("Copy. Standby."), "copy. standby");
});
