/**
 * Shared artifact builder. Given the local RF/Icecast config and a "plan" (the
 * list of talkgroups to bridge), write the three runtime files:
 *
 *   trunk-recorder/config.json      decode + UDP-stream each talkgroup
 *   icecast/icecast.xml             accept a mount per talkgroup
 *   generated/stream-talkgroups.sh  one ffmpeg per talkgroup: UDP PCM -> Icecast
 *
 * Two callers produce the plan differently:
 *   - generate.mjs        from config/system.json's `bridges[]` (offline path)
 *   - sync-from-safet.mjs from the bridges you created in the SafeT console
 *
 * A plan item: { tgid:Number, mount:String, channel:String }.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

/** First UDP port; talkgroup N streams on BASE_UDP_PORT + N. */
export const BASE_UDP_PORT = 9000;

/** Derive a talkgroup id from a `…/tg<NNN>` stream mount, or null. */
export function tgidFromMount(mountOrUrl) {
  const m = String(mountOrUrl).match(/\/?tg(\d+)\s*$/i);
  return m ? Number(m[1]) : null;
}

function buildTrunkConfig(cfg, plan) {
  const sdr = cfg.sdr ?? {};
  const sys = cfg.system ?? {};
  return {
    ver: 2,
    sources: [
      {
        center: sdr.centerHz ?? 854000000,
        rate: sdr.rateHz ?? 2400000,
        gain: sdr.gain ?? 0,
        ppm: sdr.ppm ?? 0,
        digitalRecorders: Math.max(4, plan.length),
        driver: "osmosdr",
        device: `rtl=${sdr.device ?? 0}`,
      },
    ],
    systems: [
      {
        shortName: sys.shortName ?? "occcs",
        type: sys.type ?? "p25",
        modulation: sys.modulation ?? "qpsk",
        control_channels: sys.controlChannelsHz ?? [],
        talkgroupsFile: "talkgroups.csv",
        talkgroups: plan.map((p) => Number(p.tgid)),
      },
    ],
    plugins: [
      {
        name: "simplestream",
        library: "/usr/local/lib/trunk-recorder/libsimplestream.so",
        streams: plan.map((p) => ({
          TGID: Number(p.tgid),
          address: "127.0.0.1",
          port: p.udpPort,
          sendTGID: false,
        })),
      },
    ],
    captureDir: "/tmp/trunk-recorder",
    callTimeout: 3,
    logFile: false,
  };
}

function buildIcecastXml(cfg, plan) {
  const ice = cfg.icecast ?? {};
  return `<icecast>
  <!-- Generated by sdr-bridge — edit config/system.json, not this file. -->
  <limits>
    <clients>100</clients>
    <sources>${Math.max(10, plan.length + 3)}</sources>
    <queue-size>524288</queue-size>
    <client-timeout>30</client-timeout>
    <header-timeout>15</header-timeout>
    <source-timeout>30</source-timeout>
    <burst-size>65536</burst-size>
  </limits>
  <authentication>
    <source-password>${ice.sourcePassword ?? "hackme"}</source-password>
    <relay-password>${ice.sourcePassword ?? "hackme"}</relay-password>
    <admin-user>admin</admin-user>
    <admin-password>${ice.adminPassword ?? "hackme"}</admin-password>
  </authentication>
  <hostname>${ice.host ?? "127.0.0.1"}</hostname>
  <listen-socket>
    <port>${ice.port ?? 8000}</port>
  </listen-socket>
  <fileserve>0</fileserve>
  <paths>
    <logdir>/tmp/icecast-logs</logdir>
    <webroot>/usr/share/icecast2/web</webroot>
    <adminroot>/usr/share/icecast2/admin</adminroot>
  </paths>
  <logging>
    <loglevel>2</loglevel>
  </logging>
</icecast>
`;
}

function buildStreamScript(cfg, plan) {
  const ice = cfg.icecast ?? {};
  const icePort = ice.port ?? 8000;
  const iceHost = ice.host ?? "127.0.0.1";
  const srcPass = ice.sourcePassword ?? "hackme";
  const stanzas = plan
    .map(
      (p) => `# ${p.channel}  (TGID ${p.tgid})  ->  mount /${p.mount}
ffmpeg -hide_banner -loglevel warning \\
  -f lavfi -i "anullsrc=channel_layout=mono:sample_rate=8000" \\
  -f s16le -ar 8000 -ac 1 -fflags nobuffer \\
  -i "udp://127.0.0.1:${p.udpPort}?listen=1&fifo_size=1000000&overrun_nonfatal=1" \\
  -filter_complex "[0:a][1:a]amix=inputs=2:duration=first:normalize=0,volume=1.6,alimiter=limit=0.95[a]" \\
  -map "[a]" -c:a libmp3lame -b:a 32k -ar 8000 -ac 1 \\
  -content_type audio/mpeg -f mp3 \\
  "icecast://source:${srcPass}@${iceHost}:${icePort}/${p.mount}" &
STREAMER_PIDS+=($!)`,
    )
    .join("\n\n");

  const monitorInputs = plan
    .map((p) => `  -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 2 -i "http://${iceHost}:${icePort}/${p.mount}"`)
    .join(" \\\n");
  const monitorBlock = plan.length > 0 ? `
# Monitor — pull all talkgroup mounts and mix into /monitor.
# Add one SafeT bridge: stream_url -> <base>/monitor, channel "Scanner".
(sleep 5 && ffmpeg -hide_banner -loglevel warning \\
${monitorInputs} \\
  -filter_complex "amix=inputs=${plan.length}:duration=longest:dropout_transition=0[a]" \\
  -map "[a]" -c:a libmp3lame -b:a 32k -ar 8000 -ac 1 \\
  -content_type audio/mpeg -f mp3 \\
  "icecast://source:${srcPass}@${iceHost}:${icePort}/monitor") &
STREAMER_PIDS+=($!)` : "";

  return `#!/usr/bin/env bash
# Generated by sdr-bridge — do not edit by hand.
# One ffmpeg per talkgroup: trunk-recorder UDP PCM -> Icecast mount.

STREAMER_PIDS=()
cleanup() {
  trap '' EXIT INT TERM
  echo "stopping streamers..."
  for pid in "\${STREAMER_PIDS[@]:-}"; do kill "\$pid" 2>/dev/null || true; done
}
trap cleanup EXIT INT TERM

${stanzas || "echo 'No talkgroups to stream.'"}
${monitorBlock}
# Prime all ffmpeg→Icecast connections so every mount is live before the first call.
# Sends 1 s of silence to each UDP port; ffmpeg's amix unblocks and connects immediately.
(sleep 2 && python3 -c "import socket; [socket.socket(socket.AF_INET,socket.SOCK_DGRAM).sendto(bytes(16000),('127.0.0.1',p)) for p in [${plan.map((p) => p.udpPort).join(",")}]]") &

echo "Streaming ${plan.length} talkgroup mount(s) + /monitor to icecast://${iceHost}:${icePort}/  (Ctrl-C to stop)"
wait
`;
}

/**
 * Write all three runtime files. `plan` items only need { tgid, mount, channel };
 * a UDP port is assigned here so the trunk-recorder targets and the ffmpeg
 * listeners always agree.
 */
export function writeArtifacts(root, cfg, plan) {
  const withPorts = plan.map((p, i) => ({ ...p, udpPort: BASE_UDP_PORT + i }));
  mkdirSync(join(root, "generated"), { recursive: true });
  mkdirSync(join(root, "trunk-recorder"), { recursive: true });
  mkdirSync(join(root, "icecast"), { recursive: true });

  writeFileSync(
    join(root, "trunk-recorder", "config.json"),
    JSON.stringify(buildTrunkConfig(cfg, withPorts), null, 2) + "\n",
  );
  // Always emit the talkgroups CSV trunk-recorder names calls from, so the file
  // the container mounts is guaranteed to exist (the console path may have no
  // hand-supplied config/talkgroups.csv) and calls get readable labels.
  const csv =
    "Decimal,Hex,Alpha Tag,Mode,Description,Tag,Category\n" +
    withPorts
      .map((p) => `${p.tgid},${Number(p.tgid).toString(16)},${p.channel},D,${p.channel},,SDR`)
      .join("\n") +
    "\n";
  writeFileSync(join(root, "trunk-recorder", "talkgroups.csv"), csv);
  writeFileSync(join(root, "icecast", "icecast.xml"), buildIcecastXml(cfg, withPorts));
  writeFileSync(join(root, "generated", "stream-talkgroups.sh"), buildStreamScript(cfg, withPorts), {
    mode: 0o755,
  });
  return withPorts;
}
