/**
 * SSA call-type radio pronunciations (from 10-8-alert-dashboard dispatcher-server.js).
 * Used when expanding dispatcher_response text before ElevenLabs TTS.
 */
export const CALL_TYPE_SPOKEN: Record<string, string> = {
  "187": "one eighty-seven, murder",
  "207": "two oh seven, kidnapping",
  "211": "two eleven, robbery",
  "240": "two forty, assault",
  "242": "two forty-two, battery",
  "245": "two forty-five, assault with a deadly weapon",
  "261": "two sixty-one, rape",
  "273a": "two seventy-three Alpha, child cruelty",
  "2735": "two seventy-three dot five, domestic violence",
  "288": "two eighty-eight, lewd and lascivious conduct",
  "314": "three fourteen, indecent exposure",
  "374": "three seventy-four, illegal dumping",
  "390": "three ninety, drunk person",
  "415": "four fifteen, disturbing the peace",
  "415a": "four fifteen Alpha, disturbing the peace, automobile",
  "415e": "four fifteen Echo, music or party",
  "415F": "four fifteen Foxtrot, fireworks",
  "415g": "four fifteen Golf, gang disturbance",
  "417": "four seventeen, subject with a gun",
  "451": "four fifty-one, arson",
  "459": "four fifty-nine, burglary in progress",
  "459a": "four fifty-nine, audible alarm",
  "459s": "four fifty-nine, silent alarm",
  "470": "four seventy, forgery",
  "480": "four eighty, hit and run with injury",
  "481": "four eighty-one, hit and run, no injury",
  "483": "four eighty-three, hit and run, parked vehicle",
  "484": "four eighty-four, theft",
  "487": "four eighty-seven, grand theft",
  "488": "four eighty-eight, petty theft",
  "496": "four ninety-six, stolen property",
  "11350": "eleven three fifty, controlled substance",
  "11357": "eleven three fifty-seven, marijuana",
  "502": "five oh two, drunk driver",
  "503": "five oh three, stolen vehicle",
  "504": "five oh four, car tampering",
  "505a": "five oh five a, reckless driving",
  "510": "five ten, speeding or racing vehicle",
  "586": "five eighty-six, illegally parked vehicle",
  "594": "five ninety-four, vandalism",
  "602": "six oh two, trespassing",
  "901": "nine oh one, traffic accident, unknown injuries",
  "901t": "nine oh one Tango, traffic accident with injuries",
  "902m": "nine oh two Mike, medical aid",
  "902t": "nine oh two Tango, traffic accident, no injuries",
  "904": "nine oh four, fire",
  "904A": "nine oh four Alpha, fire alarm",
  "905b": "nine oh five Bravo, animal bite",
  "905n": "nine oh five November, animal noise",
  "905s": "nine oh five Sierra, stray animal",
  "906": "nine oh six, rescue",
  "909": "nine oh nine, traffic information",
  "909c": "nine oh nine Charlie, traffic control",
  "909t": "nine oh nine Tango, traffic hazard",
  "911B": "nine eleven Bravo, contact officer",
  "914a": "nine fourteen Alpha, attempt suicide",
  "914s": "nine fourteen Sierra, suicide",
  "917a": "nine seventeen Alpha, abandoned vehicle",
  "918": "nine eighteen, mental subject",
  "918v": "nine eighteen Victor, violent mental subject",
  "919": "nine nineteen, keep the peace",
  "920a": "nine twenty adult, missing adult",
  "920c": "nine twenty child, missing child",
  "920j": "nine twenty juvie, missing juvenile",
  "921": "nine twenty-one, prowler",
  "924": "nine twenty-four, detail",
  "924d": "nine twenty-four Delta, station detail",
  "924r": "nine twenty-four Romeo, report writing",
  "925": "nine twenty-five, suspicious person",
  "925v": "nine twenty-five Victor, suspicious vehicle",
  "927": "nine twenty-seven, unknown trouble",
  "930": "nine thirty, see the man",
  "931": "nine thirty-one, see the woman",
  "932": "nine thirty-two, open door",
  "933": "nine thirty-three, open window",
  "961": "nine sixty-one, car stop",
  "966a": "nine sixty-six Alpha, shots heard",
  "982": "nine eighty-two, bomb threat",
  "983": "nine eighty-three, explosion",
  "984": "nine eighty-four, hazardous material spill",
  "995": "nine ninety-five, riot or major disturbance",
  "1014": "ten fourteen, escort",
  ca: "citizen assist",
  c5: "code five, stakeout",
  c6: "code six, out for investigation",
  c7: "code seven, lunch",
  fu: "follow up",
  info: "information only",
  notice: "issue a notice",
  mi: "maintenance issue",
  meet: "meeting",
  pc: "patrol check",
  ped: "pedestrian stop",
  prop: "property damage",
  event: "special event",
  post: "standing post",
  task: "task",
  test: "test call",
  welfare: "welfare check",
};

/**
 * Short codes that also appear in addresses or common words — only match lowercase
 * so "CA" (California) is not read as "citizen assist".
 */
export const CALL_TYPE_LOWERCASE_ONLY = new Set([
  "ca",
  "c5",
  "c6",
  "c7",
  "fu",
  "mi",
  "pc",
  "ped",
  "prop",
]);

/** Longest keys first so "925v" matches before "925". */
export function callTypeSpokenKeysByLength(): string[] {
  return Object.keys(CALL_TYPE_SPOKEN).sort((a, b) => b.length - a.length);
}
